parameters:
#    ibw_partymember.example.class: Ibw\PartymemberBundle\Example

services:
#    ibw_partymember.example:
#        class: %ibw_partymember.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    ibw.partymember.admin.partymember:
        class: Ibw\PartymemberBundle\Admin\PartymemberAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 管理, label: 党员信息 }
        arguments:
            - ~
            - Ibw\PartymemberBundle\Entity\Partymember
            - 'IbwPartymemberBundle:PartymemberAdmin'

    ibw.partymember.admin.applypartymember:
        class: Ibw\PartymemberBundle\Admin\ApplyPartymemberAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 管理, label: 申请入党信息 }
        arguments:
            - ~
            - Ibw\PartymemberBundle\Entity\ApplyPartymember
            - 'IbwPartymemberBundle:ApplyPartymemberAdmin'
    ibw.partymember.admin.partymemberbranch:
        class: Ibw\PartymemberBundle\Admin\PartymemberBranchAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 管理, label: 党支部信息 }
        arguments:
            - ~
            - Ibw\PartymemberBundle\Entity\PartymemberBranch
            - 'IbwPartymemberBundle:PartymemberBranchAdmin'            