#ibw_partymember:
#    resource: "@IbwPartymemberBundle/Resources/config/routing.yml"
#    prefix:   /
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
#    prefix: /

login:
    pattern:   /login
    defaults:  { _controller: IbwPartymemberBundle:Default:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
