security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: sonata_admin_redirect
            logout:
                path:   /logout
#                target: /admin
                target: /login
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        main:
            entity: { class: Ibw\PartymemberBundle\Entity\User, property: username }

    encoders:
        Ibw\PartymemberBundle\Entity\User: sha512